class HomePage:
    BTN_PRO_TOOLS: str = ""
    BTN_LOG_IN: str = "//button[@name = 'Log In' and contains(text(), 'Log In')]"
    BTN_SIGN_UP: str = "//button[@name = 'Sign Up' and contains(text(), 'Sign Up')]"
    BTN_BOOK_TO_BUY = ""
    BTN_BOOK_TO_SELL = ""
    BTN_BOOK_TO_RENT = ""
    TXT_SEARCH = ""
    BTN_SCOUT = ""
    HPL_FACEBOOK_ASSOCIATION = ""
    HPL_TIKTOK_ASSOCIATION = ""
    HPL_TWITTER_ASSOCIATION = ""
    HPL_INSTAGRAM_ASSOCIATION = ""
    HPL_YOUTUBE_ASSOCIATION = ""
    HPL_PINTEREST_ASSOCIATION = ""
    ALE_TOAST_SUCCESSFULLY_LOGGED_IN: str = \
        "//div[@role = 'alert']//div[contains(@class, 'toast')]//following-sibling::div"
    BTN_ACCOUNT_ICON: str = "//button[contains(@class, 'HeaderProfileButton')]"
    DDI_ACCOUNT: str = "//a[contains(@class, 'ProfileMenu')]"
    DDI_LOG_OUT: str = "//button[contains(@class, 'ProfileMenuButton')]"
