class ProfilePage:
    BTN_PROFILE = ""
    BTN_VENDORS = ""
    BTN_SUBSCRIPTION = ""
    LBL_USER_EMAIL: str = "//input[contains(@name, 'email')]"
    LBL_USER_FIRST_NAME = ""
    LBL_USER_LAST_NAME = ""
    CHK_COLLEGE_STUDENT = ""
    CHK_RECEIVE_NEWSLETTER = ""
    BTN_CHANGE_PASSWORD = ""
    LBL_ACCOUNT_TYPE = ""
    BTN_UPGRADE_TO_PRO = ""
    BTN_SAVE_SETTINGS = ""
